### PR TITLE
neuca changes to fetch data from comet when configured

### PR DESCRIPTION
**Pull request by kthare10**
Update the neuca guest tools to fetch meta data for an instance from comet when comethost is configured in global section of openstack meta data.

If comethost is not configured, the guest tools behave as before and fetch information from openstack.

This pull request changes for https://github.com/RENCI-NRIG/neuca-guest-tools/issues/3

Corresponding ORCA Changes are tracked by https://github.com/RENCI-NRIG/orca5/issues/212

### CODE REVIEW

**Review by vjorlikowski — CHANGES_REQUESTED** [review]
As I review the code, I have distinct issues that I feel need to be resolved, and must retract my earlier enthusiasm.

1) The NEucaInstanceData class is supposed to be the repository of data gathered, whether through the userData mechanism or COMET. You should wrapper things, so that you do not have to do "if getCometHost" throughout the customizer code - you should be able to reference the appropriate fields in the NEucaInstanceData object. The if/else throughout customizer.py *really* doesn't need to be that way, if NEucaInstanceData is properly managed.

2) In NEucaInstanceData - you should *not* constantly be making round-trips to COMET. The updateInstanceData() method exists to fetch data regularly into the object, and to denote whether it is fresh or stale - please check the run() loop in neuca.py.
I would suggest updating updateInstanceData() to call updateCometData(), and to integrate it with the data representation that NEucaInstanceData represents.
3) Why is neuca.py writing stdout_path to /root/comet?
If you want to log stdout, use a proper logger (with rotation). Setting stdout_path is useful for debugging during development - but should not be part of a production commit.
4) In neuca.py - why are you choosing to load the scripts returned from customized.getAllScripts() as JSON - then immediately performing json.dumps() them?
5) Please maintain the indentation style of the code as you found it; this means conforming to PEP8 indentation.

I look forward to the subsequent patch to review.

**Comment by kthare10** [comment]
Code updated with the changes from review comments.

**Comment by kthare10** [comment]
added code for using round robin to send messages to comet head nodes

**Review by mjstealey — APPROVED** [review]
Provisional +1
So long as the concerns that @vjorlikowski had mentioned are accounted for I don't have anything new to add.

**Review by vjorlikowski — CHANGES_REQUESTED** [review]
Looks much better - but:
1) Why do you have stdout_path as         self.stdout_path = '/root/comet'
in neuca.py

If you want to re-direct stdout (for debugging) - make it configurable, with a default to /dev/null

2) Again - in neuca.py - line 214 - please check indentation on "else:" ; same for line 225, line 232, line 239, and line 247

3) customizer.py and neuca.py - is the "import json" unused in these files? It *appears* to be...

These are minor items; please correct these - and I expect I will approve on next review.

**Comment by kthare10** [comment]
@vjorlikowski - I changed the stdout path for debugging while testing. I think I commit this change by mistake. I will remove this change.

**Comment by kthare10** [comment]
@vjorlikowski - fixed the open issues, please verify and close the review

**Comment by vjorlikowski** [comment]
@kthare10 

Do customizer.py and neuca.py require the "import json" - it appears unused.

**Comment by kthare10** [comment]
@vjorlikowski - json import is not required as per the new instanceData.py. removed it

**Review by vjorlikowski — COMMENTED** [review]
In customizer.py:
1) Line 1316 - what does this print, in the comment for the generated udev file, when replacing "iface[1]" with "config" - does this work when COMET is not enabled?

2) Line 1328 - cidr is set to config[2] - if config[2] is a reasonable value for cidr, how can (1) above work?

It seems to me that either (1) or (2) can be correct - but not both; can you explain how this works, in both the userdata and COMET cases?

**Comment by kthare10** [comment]
@vjorlikowski fixed and verified for both with comet and without comet

**Review by vjorlikowski — APPROVED** [review]

**Pull request merged**
